import { BankDirectoryItem, BankingTransaction, User } from '../types';

export const BANK_DIRECTORY: BankDirectoryItem[] = [
  {
    id: 'apex-premier-bank',
    name: 'Apex Premier Bank',
    shortCode: 'APEX',
    country: 'India',
    flag: '🇮🇳',
    type: 'Indian Retail & Commercial',
    tollFree: ['1800 419 8888', '1800 103 8899 (Reserve Priority)', '1860 419 8888'],
    emergencyCardBlock: 'SMS BLOCK <last 4 digits> to 5676782 or Call 1860 419 8888',
    fraudEmail: 'fraud.reporting@apexbank.in',
    swiftCode: 'APEXINBBXXX',
    headquarters: 'Financial District, Mumbai, India',
    popularServices: [
      'Apex Reserve Private Banking',
      'UPI 2.0 Real-Time Intercept',
      'Global Multi-Currency World Card',
      'Edge Security & Instant Card Lock'
    ],
    color: '#0284c7',
    badgeColor: 'bg-cyan-950/60 text-cyan-300 border-cyan-500/40',
    specialFeatures: 'Apex Reserve AI Shield Active (₹10 Lakhs Zero-Liability Fraud Insurance Guarantee)',
    isFeaturedPartner: true
  },
  {
    id: 'hdfc-bank',
    name: 'HDFC Bank',
    shortCode: 'HDFC',
    country: 'India',
    flag: '🇮🇳',
    type: 'Indian Retail & Commercial',
    tollFree: ['1800 202 6161', '1800 1600'],
    emergencyCardBlock: '1800 266 4332 or NetBanking Hotlist',
    fraudEmail: 'cybercell@hdfcbank.com',
    swiftCode: 'HDFCINBBXXX',
    headquarters: 'Mumbai, Maharashtra, India',
    popularServices: ['Infinia Super Premium', 'PayZapp Multi-Wallet', 'SmartBuy Rewards', 'SmartHub Vyapar'],
    color: '#004c8f',
    badgeColor: 'bg-[#004c8f]/20 text-[#4da8ff] border-[#004c8f]/40',
    specialFeatures: 'EVA AI Virtual Assistant with automated debit alert confirmation'
  },
  {
    id: 'icici-bank',
    name: 'ICICI Bank',
    shortCode: 'ICICI',
    country: 'India',
    flag: '🇮🇳',
    type: 'Indian Retail & Commercial',
    tollFree: ['1800 1080', '1800 102 4242'],
    emergencyCardBlock: '1800 266 7777 or SMS CCBLK <last 4 digits> to 5676766',
    fraudEmail: 'antifraud@icicibank.com',
    swiftCode: 'ICICINBBXXX',
    headquarters: 'Mumbai, Maharashtra, India',
    popularServices: ['iMobile Pay', 'Emerald Credit Card', 'InstaBIZ SME Account', 'Money2India Cross-Border'],
    color: '#f37021',
    badgeColor: 'bg-[#f37021]/20 text-[#ffa666] border-[#f37021]/40',
    specialFeatures: 'i-Safe OTP verification with tokenized device finger-printing'
  },
  {
    id: 'sbi-bank',
    name: 'State Bank of India (SBI)',
    shortCode: 'SBI',
    country: 'India',
    flag: '🇮🇳',
    type: 'Indian Retail & Commercial',
    tollFree: ['1800 1234', '1800 2100', '1800 11 2211'],
    emergencyCardBlock: 'SMS BLOCK <last 4 digits> to 567676 or Call 1800 111 109',
    fraudEmail: 'cybercrime@sbi.co.in',
    swiftCode: 'SBININBBXXX',
    headquarters: 'State Bank Bhavan, Mumbai, India',
    popularServices: ['YONO SBI SuperApp', 'Global ATM International', 'INB NetBanking', 'NRE/NRO Remittances'],
    color: '#280071',
    badgeColor: 'bg-[#280071]/30 text-[#a380ff] border-[#280071]/50',
    specialFeatures: 'Largest public sector bank network with direct integration to RBI CRILIC'
  },
  {
    id: 'chase-bank',
    name: 'JPMorgan Chase & Co.',
    shortCode: 'CHASE',
    country: 'United States',
    flag: '🇺🇸',
    type: 'Global Multinational',
    tollFree: ['1-800-935-9935', '1-877-242-7372 (Fraud Dept)'],
    emergencyCardBlock: '1-800-432-3117 (Card Services) or Chase Mobile Lock',
    fraudEmail: 'phishing@chase.com',
    swiftCode: 'CHASUS33XXX',
    headquarters: '383 Madison Ave, New York, NY, USA',
    popularServices: ['Chase Sapphire Reserve', 'Chase Private Client', 'J.P. Morgan Payments API', 'Global Treasury'],
    color: '#117aca',
    badgeColor: 'bg-[#117aca]/20 text-[#66baff] border-[#117aca]/40',
    specialFeatures: 'Real-time SWIFT gpi cross-border tracker and OFAC sanctions screener'
  },
  {
    id: 'barclays-bank',
    name: 'Barclays Bank PLC',
    shortCode: 'BARCLAYS',
    country: 'United Kingdom',
    flag: '🇬🇧',
    type: 'Global Multinational',
    tollFree: ['0800 400 100 (UK)', '+44 2476 842100 (Global)', '0800 389 1652 (Fraud)'],
    emergencyCardBlock: '+44 1604 230 230 or Barclays App Instant Freeze',
    fraudEmail: 'internetsecurity@barclays.co.uk',
    swiftCode: 'BARCGB22XXX',
    headquarters: '1 Churchill Place, London, UK',
    popularServices: ['Barclaycard Avios', 'Premier Banking Global', 'Corporate Trade Finance', 'Barclays Pingit FX'],
    color: '#00aeef',
    badgeColor: 'bg-[#00aeef]/20 text-[#66d6ff] border-[#00aeef]/40',
    specialFeatures: 'UK Confirmation of Payee (CoP) anti-push-payment fraud screening'
  },
  {
    id: 'hsbc-bank',
    name: 'HSBC Holdings',
    shortCode: 'HSBC',
    country: 'Global / UK',
    flag: '🌐',
    type: 'Global Multinational',
    tollFree: ['1800 266 3456 (India)', '1-800-975-4722 (US)', '+44 1442 422 901 (UK)'],
    emergencyCardBlock: '+44 1442 422 901 or HSBC India Emergency 1800 102 2208',
    fraudEmail: 'security@hsbc.com',
    swiftCode: 'HSBCINBBXXX',
    headquarters: '8 Canada Square, London, UK',
    popularServices: ['HSBC Premier Worldwide', 'Global Money Account', 'Everyday Global Debit', 'Omni Collect'],
    color: '#db0011',
    badgeColor: 'bg-[#db0011]/20 text-[#ff6675] border-[#db0011]/40',
    specialFeatures: 'Global View and Global Transfer across 30+ international markets'
  },
  {
    id: 'citi-bank',
    name: 'Citibank N.A.',
    shortCode: 'CITI',
    country: 'United States',
    flag: '🇺🇸',
    type: 'Global Multinational',
    tollFree: ['1-800-374-9700', '+1-210-677-0065 (International)'],
    emergencyCardBlock: '1-800-950-5114 or Citi Mobile Quick Lock',
    fraudEmail: 'spoof@citicorp.com',
    swiftCode: 'CITIUS33XXX',
    headquarters: '388 Greenwich St, New York, NY, USA',
    popularServices: ['Citi Prestige', 'Citigold Private Client', 'Citi Commercial Cross-Border', 'Virtual Card Numbers'],
    color: '#003b70',
    badgeColor: 'bg-[#003b70]/30 text-[#5cb3ff] border-[#003b70]/50',
    specialFeatures: 'Dynamic tokenized virtual credit cards for zero-risk online shopping'
  },
  {
    id: 'dbs-bank',
    name: 'DBS Bank Ltd',
    shortCode: 'DBS',
    country: 'Singapore',
    flag: '🇸🇬',
    type: 'Global Multinational',
    tollFree: ['1800 111 1111 (SG)', '1800 209 4555 (India)'],
    emergencyCardBlock: '+65 6327 2265 or digibank Self-Lock',
    fraudEmail: 'stopfraud@dbs.com',
    swiftCode: 'DBSSSG22XXX',
    headquarters: 'Marina Bay Financial Centre, Singapore',
    popularServices: ['digibank by DBS', 'DBS Treasures', 'Multi-Currency Autosave', 'DBS IDEAL Corporate'],
    color: '#e60000',
    badgeColor: 'bg-[#e60000]/20 text-[#ff6666] border-[#e60000]/40',
    specialFeatures: 'Digibank Payment Guard: biometric step-up for unusual international transfers'
  },
  {
    id: 'cybercrime-gov',
    name: 'National Cybercrime Reporting Portal (MHA / I4C)',
    shortCode: 'I4C-1930',
    country: 'India (Government Helpline)',
    flag: '🛡️',
    type: 'Government & Regulatory',
    tollFree: ['1930 (Immediate 24x7 Citizen Cyber Fraud Helpline)'],
    emergencyCardBlock: 'Call 1930 immediately to freeze debit money trail in Indian Banking Grid',
    fraudEmail: 'complaints@cybercrime.gov.in',
    swiftCode: 'N/A (Central Regulatory Coordination)',
    headquarters: 'Ministry of Home Affairs, New Delhi, India',
    popularServices: [
      'Citizen Financial Cyber Fraud Reporting System (CFCFRS)',
      'Inter-Bank Golden Hour Account Freeze Integration',
      'SIM/IMEI Blacklisting via DoT Sanchar Saathi',
      'Official FIR/Complaint Registration'
    ],
    color: '#059669',
    badgeColor: 'bg-emerald-950/60 text-emerald-300 border-emerald-500/40',
    specialFeatures: 'Direct API interconnect with RBI, NPCI, Apex Bank, HDFC, SBI and 250+ Indian banks'
  }
];

export const DEMO_USERS: User[] = [
  {
    id: 'USR-8921',
    name: 'Praveen Srinivas',
    email: 'praveen.analyst@apexbank.in',
    user_type: 'bank_staff',
    role: 'Senior Fraud Analyst',
    department: 'Financial Crime & ML Risk Intelligence',
    bank_name: 'Apex Premier Bank & Global Grid',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    createdAt: '2026-01-15'
  },
  {
    id: 'USR-4011',
    name: 'Vikramaditya Rao',
    email: 'vikram.rao@reserve.apexbank.in',
    user_type: 'customer',
    role: 'Apex Reserve Private Client',
    bank_name: 'Apex Premier Bank',
    account_number: '9180 2004 8831 4920',
    customer_id: 'APEX-CUST-8821',
    balance: 842500,
    currency: 'INR',
    phone: '+91 98490 12345',
    createdAt: '2023-04-10'
  },
  {
    id: 'USR-7023',
    name: 'Sarah Jenkins',
    email: 's.jenkins@jpmorgan-client.com',
    user_type: 'customer',
    role: 'International Corporate Client',
    bank_name: 'JPMorgan Chase & Co.',
    account_number: '4820 9130 5510 9942',
    customer_id: 'CHASE-GLOBAL-9031',
    balance: 148200,
    currency: 'USD',
    phone: '+1 212 555 0192',
    createdAt: '2024-08-20'
  },
  {
    id: 'USR-3199',
    name: 'Ananya Sharma',
    email: 'ananya.sharma92@gmail.com',
    user_type: 'customer',
    role: 'Retail Banking Customer',
    bank_name: 'HDFC Bank',
    account_number: '5010 0341 9920 1049',
    customer_id: 'HDFC-CUST-1049',
    balance: 76400,
    currency: 'INR',
    phone: '+91 99887 76655',
    createdAt: '2025-02-14'
  }
];

export const INITIAL_PAYMENT_RECORDS: BankingTransaction[] = [
  {
    id: 'PAY-APEX-98372',
    transaction_id: 'APEX-UTR-98372',
    customer_id: 'APEX-CUST-8821',
    amount: 92000,
    currency: 'INR',
    bank_name: 'Apex Premier Bank',
    payment_mode: 'NetBanking',
    beneficiary_name: 'Emirates Gold & Luxury Souk',
    beneficiary_account: 'AE44 0330 0000 8921 44',
    reference_utr: 'APEX20260917022418001',
    transaction_type: 'online',
    merchant_category: 'luxury_jewelry',
    location: 'Dubai, UAE',
    device_type: 'vpn_proxy',
    is_international: true,
    hour: 2,
    timestamp: '2026-09-17 02:24:18',
    status: 'Fraud',
    risk_level: 'HIGH',
    fraud_probability: 0.942,
    risk_score: 94,
    failed_attempts: 3,
    previous_transaction_amount: 3200,
    transactions_last_24h: 9,
    transactions_last_1h: 4,
    is_new_device: true,
    is_new_location: true,
    action_taken: 'Blocked',
    dispute_status: 'Under Investigation',
    dispute_reason: 'Customer reported uninitiated international transaction while sleeping in Mumbai.'
  },
  {
    id: 'PAY-CHASE-002',
    transaction_id: 'CHASE-WIRE-7731',
    customer_id: 'CHASE-GLOBAL-9031',
    amount: 85000,
    currency: 'USD',
    bank_name: 'JPMorgan Chase & Co.',
    payment_mode: 'SWIFT Wire',
    beneficiary_name: 'Binance Crypto Liquidity Desk',
    beneficiary_account: 'US77 CHAS 0001 9284 55',
    reference_utr: 'CHASUS202609170158',
    transaction_type: 'online',
    merchant_category: 'gaming_crypto',
    location: 'New York, USA',
    device_type: 'new_mobile',
    is_international: false,
    hour: 3,
    timestamp: '2026-09-17 01:58:10',
    status: 'Fraud',
    risk_level: 'HIGH',
    fraud_probability: 0.917,
    risk_score: 92,
    failed_attempts: 2,
    previous_transaction_amount: 4100,
    transactions_last_24h: 7,
    transactions_last_1h: 3,
    is_new_device: true,
    is_new_location: true,
    action_taken: 'Blocked',
    dispute_status: 'None'
  },
  {
    id: 'PAY-APEX-001',
    transaction_id: 'APEX-UPI-10492',
    customer_id: 'APEX-CUST-8821',
    amount: 2500,
    currency: 'INR',
    bank_name: 'Apex Premier Bank',
    payment_mode: 'UPI',
    beneficiary_name: 'Amazon India Pvt Ltd',
    beneficiary_account: 'amazonpay@apexbank',
    reference_utr: 'APEXUPI49182749',
    transaction_type: 'online',
    merchant_category: 'shopping',
    location: 'Vijayawada, India',
    device_type: 'trusted_mobile',
    is_international: false,
    hour: 14,
    timestamp: '2026-09-16 14:12:05',
    status: 'Legitimate',
    risk_level: 'LOW',
    fraud_probability: 0.032,
    risk_score: 3,
    failed_attempts: 0,
    previous_transaction_amount: 2100,
    transactions_last_24h: 2,
    transactions_last_1h: 0,
    is_new_device: false,
    is_new_location: false,
    action_taken: 'Approved',
    dispute_status: 'None'
  },
  {
    id: 'PAY-HDFC-003',
    transaction_id: 'HDFC-UPI-5512',
    customer_id: 'HDFC-CUST-1049',
    amount: 1200,
    currency: 'INR',
    bank_name: 'HDFC Bank',
    payment_mode: 'UPI',
    beneficiary_name: 'Blinkit Instant Groceries',
    beneficiary_account: 'blinkit@hdfcbank',
    reference_utr: 'HDFCUPI99182740',
    transaction_type: 'upi',
    merchant_category: 'grocery',
    location: 'Hyderabad, India',
    device_type: 'trusted_mobile',
    is_international: false,
    hour: 11,
    timestamp: '2026-09-16 11:34:22',
    status: 'Legitimate',
    risk_level: 'LOW',
    fraud_probability: 0.021,
    risk_score: 2,
    failed_attempts: 0,
    previous_transaction_amount: 950,
    transactions_last_24h: 3,
    transactions_last_1h: 1,
    is_new_device: false,
    is_new_location: false,
    action_taken: 'Approved',
    dispute_status: 'None'
  },
  {
    id: 'PAY-BARCLAYS-006',
    transaction_id: 'BARC-WIRE-9031',
    customer_id: 'BARC-CUST-9031',
    amount: 45000,
    currency: 'GBP',
    bank_name: 'Barclays Bank PLC',
    payment_mode: 'Credit Card',
    beneficiary_name: 'British Airways First Class',
    beneficiary_account: 'GB29 BARC 2000 0055 99',
    reference_utr: 'BARC20260916231940',
    transaction_type: 'online',
    merchant_category: 'travel',
    location: 'London, UK',
    device_type: 'desktop_browser',
    is_international: true,
    hour: 23,
    timestamp: '2026-09-16 23:19:40',
    status: 'Under Review',
    risk_level: 'MEDIUM',
    fraud_probability: 0.584,
    risk_score: 58,
    failed_attempts: 1,
    previous_transaction_amount: 8000,
    transactions_last_24h: 4,
    transactions_last_1h: 1,
    is_new_device: true,
    is_new_location: true,
    action_taken: 'OTP Requested',
    dispute_status: 'None'
  },
  {
    id: 'PAY-ICICI-005',
    transaction_id: 'ICICI-POS-2190',
    customer_id: 'ICICI-CUST-2190',
    amount: 12500,
    currency: 'INR',
    bank_name: 'ICICI Bank',
    payment_mode: 'Debit Card',
    beneficiary_name: 'Croma Megastore Bengaluru',
    beneficiary_account: 'croma@icici',
    reference_utr: 'ICICIPOS992144',
    transaction_type: 'pos',
    merchant_category: 'shopping',
    location: 'Bengaluru, India',
    device_type: 'trusted_mobile',
    is_international: false,
    hour: 16,
    timestamp: '2026-09-16 16:40:11',
    status: 'Legitimate',
    risk_level: 'LOW',
    fraud_probability: 0.085,
    risk_score: 9,
    failed_attempts: 0,
    previous_transaction_amount: 11000,
    transactions_last_24h: 2,
    transactions_last_1h: 0,
    is_new_device: false,
    is_new_location: false,
    action_taken: 'Approved',
    dispute_status: 'None'
  },
  {
    id: 'PAY-SBI-007',
    transaction_id: 'SBI-ATM-6110',
    customer_id: 'SBI-CUST-6110',
    amount: 3400,
    currency: 'INR',
    bank_name: 'State Bank of India (SBI)',
    payment_mode: 'Debit Card',
    beneficiary_name: 'SBI ATM Anna Nagar East',
    beneficiary_account: 'SBIN-ATM-TN-401',
    reference_utr: 'SBIATM090512441',
    transaction_type: 'atm',
    merchant_category: 'utilities',
    location: 'Chennai, India',
    device_type: 'trusted_mobile',
    is_international: false,
    hour: 9,
    timestamp: '2026-09-16 09:05:12',
    status: 'Legitimate',
    risk_level: 'LOW',
    fraud_probability: 0.018,
    risk_score: 2,
    failed_attempts: 0,
    previous_transaction_amount: 2500,
    transactions_last_24h: 1,
    transactions_last_1h: 0,
    is_new_device: false,
    is_new_location: false,
    action_taken: 'Approved',
    dispute_status: 'None'
  },
  {
    id: 'PAY-HSBC-008',
    transaction_id: 'HSBC-SWIFT-4419',
    customer_id: 'HSBC-CUST-4419',
    amount: 110000,
    currency: 'USD',
    bank_name: 'HSBC Holdings',
    payment_mode: 'SWIFT Wire',
    beneficiary_name: 'Apex Crypto Exchange Offshore',
    beneficiary_account: 'SG79 HSBC 9940 1120 44',
    reference_utr: 'HSBCSWIFT202609160344',
    transaction_type: 'wire',
    merchant_category: 'gaming_crypto',
    location: 'Singapore',
    device_type: 'jailbroken_device',
    is_international: true,
    hour: 3,
    timestamp: '2026-09-16 03:44:59',
    status: 'Fraud',
    risk_level: 'HIGH',
    fraud_probability: 0.965,
    risk_score: 97,
    failed_attempts: 3,
    previous_transaction_amount: 6000,
    transactions_last_24h: 8,
    transactions_last_1h: 3,
    is_new_device: true,
    is_new_location: true,
    action_taken: 'Blocked',
    dispute_status: 'Resolved Refunded',
    dispute_reason: 'Flagged by HSBC Global Fraud Intercept and reversed to account.'
  },
  {
    id: 'PAY-APEX-009',
    transaction_id: 'APEX-POS-3281',
    customer_id: 'APEX-CUST-8821',
    amount: 7800,
    currency: 'INR',
    bank_name: 'Apex Premier Bank',
    payment_mode: 'Credit Card',
    beneficiary_name: 'Reliance Digital Phoenix Mall',
    beneficiary_account: 'reldigital@apexbank',
    reference_utr: 'APEXPOS19221599',
    transaction_type: 'online',
    merchant_category: 'electronics',
    location: 'Pune, India',
    device_type: 'trusted_mobile',
    is_international: false,
    hour: 19,
    timestamp: '2026-09-15 19:22:15',
    status: 'Legitimate',
    risk_level: 'LOW',
    fraud_probability: 0.062,
    risk_score: 6,
    failed_attempts: 0,
    previous_transaction_amount: 5500,
    transactions_last_24h: 2,
    transactions_last_1h: 0,
    is_new_device: false,
    is_new_location: false,
    action_taken: 'Approved',
    dispute_status: 'None'
  }
];
