import { BankingTransaction } from '../types';

export const INITIAL_TRANSACTIONS: BankingTransaction[] = [
  {
    id: 'TXN-98372',
    transaction_id: 'TXN98372',
    customer_id: 'CUST-8821',
    amount: 92000,
    transaction_type: 'online',
    merchant_category: 'luxury_jewelry',
    location: 'Dubai, UAE',
    device_type: 'vpn_proxy',
    is_international: true,
    hour: 2,
    timestamp: '2026-09-17 02:24:18',
    status: 'Fraud',
    risk_level: 'HIGH',
    fraud_probability: 0.942,
    risk_score: 94,
    failed_attempts: 3,
    previous_transaction_amount: 3200,
    transactions_last_24h: 9,
    transactions_last_1h: 4,
    is_new_device: true,
    is_new_location: true,
    action_taken: 'Blocked'
  },
  {
    id: 'TXN-002',
    transaction_id: 'TXN002',
    customer_id: 'CUST-3942',
    amount: 85000,
    transaction_type: 'online',
    merchant_category: 'gaming_crypto',
    location: 'Mumbai',
    device_type: 'new_mobile',
    is_international: false,
    hour: 3,
    timestamp: '2026-09-17 01:58:10',
    status: 'Fraud',
    risk_level: 'HIGH',
    fraud_probability: 0.917,
    risk_score: 92,
    failed_attempts: 2,
    previous_transaction_amount: 4100,
    transactions_last_24h: 7,
    transactions_last_1h: 3,
    is_new_device: true,
    is_new_location: true,
    action_taken: 'Blocked'
  },
  {
    id: 'TXN-001',
    transaction_id: 'TXN001',
    customer_id: 'CUST-1049',
    amount: 2500,
    transaction_type: 'online',
    merchant_category: 'shopping',
    location: 'Vijayawada',
    device_type: 'trusted_mobile',
    is_international: false,
    hour: 14,
    timestamp: '2026-09-16 14:12:05',
    status: 'Legitimate',
    risk_level: 'LOW',
    fraud_probability: 0.032,
    risk_score: 3,
    failed_attempts: 0,
    previous_transaction_amount: 2100,
    transactions_last_24h: 2,
    transactions_last_1h: 0,
    is_new_device: false,
    is_new_location: false,
    action_taken: 'Approved'
  },
  {
    id: 'TXN-003',
    transaction_id: 'TXN003',
    customer_id: 'CUST-5512',
    amount: 1200,
    transaction_type: 'upi',
    merchant_category: 'grocery',
    location: 'Hyderabad',
    device_type: 'trusted_mobile',
    is_international: false,
    hour: 11,
    timestamp: '2026-09-16 11:34:22',
    status: 'Legitimate',
    risk_level: 'LOW',
    fraud_probability: 0.021,
    risk_score: 2,
    failed_attempts: 0,
    previous_transaction_amount: 950,
    transactions_last_24h: 3,
    transactions_last_1h: 1,
    is_new_device: false,
    is_new_location: false,
    action_taken: 'Approved'
  },
  {
    id: 'TXN-004',
    transaction_id: 'TXN004',
    customer_id: 'CUST-7741',
    amount: 64000,
    transaction_type: 'wire',
    merchant_category: 'electronics',
    location: 'Delhi NCR',
    device_type: 'emulator',
    is_international: false,
    hour: 4,
    timestamp: '2026-09-16 04:15:33',
    status: 'Fraud',
    risk_level: 'HIGH',
    fraud_probability: 0.885,
    risk_score: 89,
    failed_attempts: 3,
    previous_transaction_amount: 5000,
    transactions_last_24h: 6,
    transactions_last_1h: 2,
    is_new_device: true,
    is_new_location: true,
    action_taken: 'Blocked'
  },
  {
    id: 'TXN-005',
    transaction_id: 'TXN005',
    customer_id: 'CUST-2190',
    amount: 12500,
    transaction_type: 'pos',
    merchant_category: 'shopping',
    location: 'Bengaluru',
    device_type: 'trusted_mobile',
    is_international: false,
    hour: 16,
    timestamp: '2026-09-16 16:40:11',
    status: 'Legitimate',
    risk_level: 'LOW',
    fraud_probability: 0.085,
    risk_score: 9,
    failed_attempts: 0,
    previous_transaction_amount: 11000,
    transactions_last_24h: 2,
    transactions_last_1h: 0,
    is_new_device: false,
    is_new_location: false,
    action_taken: 'Approved'
  },
  {
    id: 'TXN-006',
    transaction_id: 'TXN006',
    customer_id: 'CUST-9031',
    amount: 45000,
    transaction_type: 'online',
    merchant_category: 'travel',
    location: 'London, UK',
    device_type: 'desktop_browser',
    is_international: true,
    hour: 23,
    timestamp: '2026-09-16 23:19:40',
    status: 'Under Review',
    risk_level: 'MEDIUM',
    fraud_probability: 0.584,
    risk_score: 58,
    failed_attempts: 1,
    previous_transaction_amount: 8000,
    transactions_last_24h: 4,
    transactions_last_1h: 1,
    is_new_device: true,
    is_new_location: true,
    action_taken: 'OTP Requested'
  },
  {
    id: 'TXN-007',
    transaction_id: 'TXN007',
    customer_id: 'CUST-6110',
    amount: 3400,
    transaction_type: 'atm',
    merchant_category: 'utilities',
    location: 'Chennai',
    device_type: 'trusted_mobile',
    is_international: false,
    hour: 9,
    timestamp: '2026-09-16 09:05:12',
    status: 'Legitimate',
    risk_level: 'LOW',
    fraud_probability: 0.018,
    risk_score: 2,
    failed_attempts: 0,
    previous_transaction_amount: 2500,
    transactions_last_24h: 1,
    transactions_last_1h: 0,
    is_new_device: false,
    is_new_location: false,
    action_taken: 'Approved'
  },
  {
    id: 'TXN-008',
    transaction_id: 'TXN008',
    customer_id: 'CUST-4419',
    amount: 110000,
    transaction_type: 'wire',
    merchant_category: 'gaming_crypto',
    location: 'Singapore',
    device_type: 'jailbroken_device',
    is_international: true,
    hour: 3,
    timestamp: '2026-09-16 03:44:59',
    status: 'Fraud',
    risk_level: 'HIGH',
    fraud_probability: 0.965,
    risk_score: 97,
    failed_attempts: 3,
    previous_transaction_amount: 6000,
    transactions_last_24h: 8,
    transactions_last_1h: 3,
    is_new_device: true,
    is_new_location: true,
    action_taken: 'Blocked'
  },
  {
    id: 'TXN-009',
    transaction_id: 'TXN009',
    customer_id: 'CUST-3281',
    amount: 7800,
    transaction_type: 'online',
    merchant_category: 'electronics',
    location: 'Pune',
    device_type: 'trusted_mobile',
    is_international: false,
    hour: 19,
    timestamp: '2026-09-15 19:22:15',
    status: 'Legitimate',
    risk_level: 'LOW',
    fraud_probability: 0.062,
    risk_score: 6,
    failed_attempts: 0,
    previous_transaction_amount: 5500,
    transactions_last_24h: 2,
    transactions_last_1h: 0,
    is_new_device: false,
    is_new_location: false,
    action_taken: 'Approved'
  },
  {
    id: 'TXN-010',
    transaction_id: 'TXN010',
    customer_id: 'CUST-1049',
    amount: 28500,
    transaction_type: 'online',
    merchant_category: 'luxury_jewelry',
    location: 'Vijayawada',
    device_type: 'trusted_mobile',
    is_international: false,
    hour: 15,
    timestamp: '2026-09-15 15:08:44',
    status: 'Under Review',
    risk_level: 'MEDIUM',
    fraud_probability: 0.482,
    risk_score: 48,
    failed_attempts: 1,
    previous_transaction_amount: 2500,
    transactions_last_24h: 3,
    transactions_last_1h: 1,
    is_new_device: false,
    is_new_location: false,
    action_taken: 'OTP Requested'
  },
  {
    id: 'TXN-011',
    transaction_id: 'TXN011',
    customer_id: 'CUST-7741',
    amount: 1850,
    transaction_type: 'upi',
    merchant_category: 'grocery',
    location: 'Kolkata',
    device_type: 'trusted_mobile',
    is_international: false,
    hour: 12,
    timestamp: '2026-09-15 12:45:00',
    status: 'Legitimate',
    risk_level: 'LOW',
    fraud_probability: 0.015,
    risk_score: 2,
    failed_attempts: 0,
    previous_transaction_amount: 1500,
    transactions_last_24h: 2,
    transactions_last_1h: 0,
    is_new_device: false,
    is_new_location: false,
    action_taken: 'Approved'
  }
];

export const HOURLY_FRAUD_DISTRIBUTION = [
  { hour: '00:00', total: 420, fraud: 38, legitimate: 382, fraudRate: 9.0 },
  { hour: '01:00', total: 310, fraud: 45, legitimate: 265, fraudRate: 14.5 },
  { hour: '02:00', total: 240, fraud: 62, legitimate: 178, fraudRate: 25.8 },
  { hour: '03:00', total: 190, fraud: 58, legitimate: 132, fraudRate: 30.5 },
  { hour: '04:00', total: 180, fraud: 42, legitimate: 138, fraudRate: 23.3 },
  { hour: '05:00', total: 290, fraud: 21, legitimate: 269, fraudRate: 7.2 },
  { hour: '06:00', total: 680, fraud: 12, legitimate: 668, fraudRate: 1.8 },
  { hour: '07:00', total: 1120, fraud: 8, legitimate: 1112, fraudRate: 0.7 },
  { hour: '08:00', total: 1890, fraud: 14, legitimate: 1876, fraudRate: 0.7 },
  { hour: '09:00', total: 2450, fraud: 18, legitimate: 2432, fraudRate: 0.7 },
  { hour: '10:00', total: 2980, fraud: 24, legitimate: 2956, fraudRate: 0.8 },
  { hour: '11:00', total: 3200, fraud: 22, legitimate: 3178, fraudRate: 0.7 },
  { hour: '12:00', total: 3150, fraud: 19, legitimate: 3131, fraudRate: 0.6 },
  { hour: '13:00', total: 2800, fraud: 15, legitimate: 2785, fraudRate: 0.5 },
  { hour: '14:00', total: 2900, fraud: 21, legitimate: 2879, fraudRate: 0.7 },
  { hour: '15:00', total: 3050, fraud: 26, legitimate: 3024, fraudRate: 0.9 },
  { hour: '16:00', total: 3210, fraud: 28, legitimate: 3182, fraudRate: 0.9 },
  { hour: '17:00', total: 3400, fraud: 31, legitimate: 3369, fraudRate: 0.9 },
  { hour: '18:00', total: 3600, fraud: 33, legitimate: 3567, fraudRate: 0.9 },
  { hour: '19:00', total: 3800, fraud: 35, legitimate: 3765, fraudRate: 0.9 },
  { hour: '20:00', total: 3500, fraud: 30, legitimate: 3470, fraudRate: 0.9 },
  { hour: '21:00', total: 2900, fraud: 29, legitimate: 2871, fraudRate: 1.0 },
  { hour: '22:00', total: 2100, fraud: 34, legitimate: 2066, fraudRate: 1.6 },
  { hour: '23:00', total: 1300, fraud: 41, legitimate: 1259, fraudRate: 3.2 }
];

export const CATEGORY_RISK_DISTRIBUTION = [
  { category: 'Gaming & Crypto', totalAmount: '₹8.4 Cr', fraudPct: 18.2, count: 1840 },
  { category: 'Luxury & Jewelry', totalAmount: '₹14.2 Cr', fraudPct: 14.6, count: 1290 },
  { category: 'Electronics', totalAmount: '₹22.1 Cr', fraudPct: 9.8, count: 4890 },
  { category: 'Travel & Airlines', totalAmount: '₹18.6 Cr', fraudPct: 6.4, count: 3420 },
  { category: 'Online Retail', totalAmount: '₹39.5 Cr', fraudPct: 3.8, count: 9850 },
  { category: 'Dining & Food', totalAmount: '₹9.2 Cr', fraudPct: 1.2, count: 6200 },
  { category: 'Utilities & Bills', totalAmount: '₹12.0 Cr', fraudPct: 0.4, count: 8900 }
];
